#!/usr/bin/env bash
# 04-env.sh — interactive .env builder for /var/www/api.nexus-x.cloud/.env
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run as root."
    exit 1
fi

ENV_FILE=/var/www/api.nexus-x.cloud/.env

if [[ -f "$ENV_FILE" ]]; then
    read -rp "$ENV_FILE already exists. Overwrite? [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
    cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
fi

rand() { openssl rand -hex 32; }

# URL-encode for use inside DATABASE_URL (handles @ : / ? # & = space etc.)
urlenc() {
    python3 -c 'import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=""))' "$1" 2>/dev/null \
    || node -e 'process.stdout.write(encodeURIComponent(process.argv[1]))' "$1"
}

read -rp "Database name [nexusx]: " DB_NAME; DB_NAME=${DB_NAME:-nexusx}
read -rp "Database user [nexusx]: " DB_USER; DB_USER=${DB_USER:-nexusx}
read -rsp "Database password: " DB_PASS; echo
read -rp "Public site URL [https://buy.nexus-x.cloud]: " SITE; SITE=${SITE:-https://buy.nexus-x.cloud}
read -rp "Public API URL  [https://api.nexus-x.cloud]: " API;  API=${API:-https://api.nexus-x.cloud}
JWT_SECRET="$(rand)"
REFRESH_SECRET="$(rand)"
DB_USER_ENC="$(urlenc "$DB_USER")"
DB_PASS_ENC="$(urlenc "$DB_PASS")"

cat > "$ENV_FILE" <<EOF
# Generated by vps/scripts/04-env.sh on $(date -u)
NODE_ENV=production
PORT=8080

# Database (password is URL-encoded so special chars like @ work)
DATABASE_URL=postgresql://${DB_USER_ENC}:${DB_PASS_ENC}@localhost:5432/${DB_NAME}
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD='$DB_PASS'

# Auth
JWT_SECRET=$JWT_SECRET
REFRESH_SECRET=$REFRESH_SECRET
JWT_EXPIRES_IN=15m
REFRESH_EXPIRES_IN=30d

# CORS / URLs
SITE_URL=$SITE
API_URL=$API
CORS_ORIGINS=$SITE

# Storage
UPLOAD_DIR=/var/www/api.nexus-x.cloud/uploads
UPLOAD_PUBLIC_BASE=$API/uploads

# Email (fill if you use SMTP)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM="NexusX <noreply@nexus-x.cloud>"
EOF

chown deploy:deploy "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo
echo "✓ Wrote $ENV_FILE"
echo "Edit it any time to adjust SMTP or other settings."
echo "After your first GitHub deploy, the API will read this file automatically."